name: study_progress_tracker
description: Study Progress Tracker - Android app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
